apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cc3test-api
  namespace: {{ .Values.cc3test.namespace }}
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          volumes:
            - name: cc3test-config
              configMap:
                name: cc3test-config
          containers:
          - name: cc3test-api
            image: {{ required ".Values.global.registry variable missing" .Values.global.registry }}/{{ required ".Values.cc3test.image.name variable missing" .Values.cc3test.image.name }}:{{ required ".Values.cc3test.image.tag variable missing" .Values.cc3test.image.tag }}
            args: ['pytest', '--disable-pytest-warnings', '--no-header', '--color=yes', '--variables', 'config/config.yaml', '-r', 'ap', '-m', 'api', 'tests']
            volumeMounts:
              - name: cc3test-config
                mountPath: /cc3test/config
                readOnly: true
          restartPolicy: Never
