apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cc3test-certificate
  namespace: {{ .Values.cc3test.namespace }}
spec:
  schedule: "*/55 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          volumes:
            - name: cc3test-config
              configMap:
                name: cc3test-config
          containers:
          - name: certificate
            image: {{ required ".Values.global.registry variable missing" .Values.global.registry }}/{{ required ".Values.cc3test.image.name variable missing" .Values.cc3test.image.name }}:{{ required ".Values.cc3test.image.tag variable missing" .Values.cc3test.image.tag }}
            command: ["/bin/sh"]
            args: ["-c", "pytest --disable-pytest-warnings --no-header --color=yes --variables config/config.yaml -m certificate -r ap tests"]
            volumeMounts:
              - name: cc3test-config
                mountPath: /cc3test/config
                readOnly: true
          restartPolicy: Never
