apiVersion: v1
kind: Secret
metadata:
  name: swift-secret
data:
  dispersion_password: {{ .Values.dispersion_password | b64enc }}
{{- range $cluster_id, $cluster := .Values.clusters }}
  {{ $cluster_id }}_service_password: {{ required ".Values.$cluster_id.swift_service_password" $cluster.swift_service_password | b64enc }}
{{end}}
